// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI operations (validate, generate, migrate) use a direct, non-pooled
    // connection. DATABASE_URL (pgbouncer pooler) stays reserved for the
    // application runtime client in src/lib/prisma.ts.
    // Also falls back to POSTGRES_URL_NON_POOLING / POSTGRES_PRISMA_URL for
    // environments configured with Vercel's Supabase Integration.
    url:
      process.env["DIRECT_URL"] ||
      process.env["POSTGRES_URL_NON_POOLING"] ||
      process.env["DATABASE_URL"] ||
      process.env["POSTGRES_PRISMA_URL"] ||
      process.env["POSTGRES_URL"],
  },
});
